@startuml 
title Diagrama General


class Ciudad{
    - nombre : String
    + visitar(grado, lugar) : Pista
    + nombre() : String

}
class Partida{
    - policiaACargo : Policia
    - ladronBuscado : Ladron
    + {static} registrarPoliciaACargo()
    + {static} registrarLadron()
    + comenzarPartida()
    + viajar(ciudad)
    + mostrarPista()
    + entrarEdificio(lugar)
}

class Comisaria{
    + ordenDeArresto(sospechoso)
    + atrapado(sospechoso) : boolean
}
class Ladron{
    - descripcion : String
    + comparar(sospechoso) : boolean
}

class Policia{
    - grado : GradoDePolicia
    - sospechoso : Ladron
    - ciudadActual : Ciudad
    - cantLugaresVisitados : Integer
    + viajar(ciudad) : Ciudad
    + entrarEdificio(lugar) : Pista
    + ordenDeArresto()
    + capturar() : boolean
}

abstract Mapa{
    -posicionesDeCiudades[]
    +obtenerPosicion(): Posicion
}

interface GradoDePolicia{
    + calcularTiempoDeViaje(kilometros) : int
}

interface LugaresDeInteres{
    + buscarPista(grado) : Pista
}

interface Pista{
    + obtenerPista() : Pista
}

interface ObjetoRobado{
    - cantidadPaises : int
	+ obtenerObjeto() : Objeto
}

interface Tiempo{
    - tiempo : int
    + tiempoTotal(tiempo) : int
}


Partida "1" --o "1..*" Ladron
Partida"1" --* "1"Policia
Partida --o Tiempo
Policia --* GradoDePolicia
Policia --> Comisaria
Policia --> Mapa
Partida "1" --* "1..*" Ciudad
Policia --> Ciudad
Ciudad "1" --> "1..5"LugaresDeInteres
LugaresDeInteres "1" --o "1..*" Pista
Ladron --* "1..*" ObjetoRobado
Comisaria --o "*" Ladron

@enduml