@startuml
title Detective sufre una herida de cuchillo y luego duerme
actor "Jugador" as AlgoThief
participant ":Ladron" as Ladron
participant ":Policia" as Policia
AlgoThief ->> Ladron : acuchillar(Policia)
activate Ladron
Ladron ->> Policia : recibirCuchillazo()
Policia --> Ladron : [1]
return [1]
deactivate Ladron
AlgoThief ->> AlgoThief : assertEquals(1, tiempoAcuchillado)
AlgoThief ->> Policia : dormir()
return[8]
AlgoThief ->> AlgoThief : assertEquals(8, tiempoQueDuerme)
@enduml