@startuml
title El detective comienza en Montreal, entra al banco y pide una pista

actor "Jugador" as AlgoThief
participant ":Policia" as Policia
participant "Montreal:Ciudad" as Ciudad
participant ":Detective" as Grado
participant "sospechoso:Ladron" as Ladron

AlgoThief ->> Policia : registroPolicia("Tesoro nacional de Montreal", cantidadArrestos, Montreal, mapa)
activate Policia
Policia ->> Grado : new()
Policia ->> Ladron : new("Tesoro Nacional de Montreal")
deactivate Policia
AlgoThief ->> Policia : anotarGenero("Femenino")
AlgoThief ->> Policia : entrarEdificio("banco")
activate Policia
Policia ->> Ciudad : visitar("banco", Detective)
return [1]
deactivate Policia
AlgoThief ->> AlgoThief : assertEquals(1, tiempoDeEntrarEdificio)
note across: El resultado es el tiempo medido en horas
@enduml