@startuml
title El detective comienza en Montreal, entra al banco y pide una pista

actor "Jugador" as AlgoThief
participant ":Policia" as Policia
participant ":Pista" as Pista
participant ":Tiempo" as Tiempo
AlgoThief ->> Policia : entrarEdificio(banco, cronometro, dado, ciudadSiguiente)
return[pistaObtenida]

AlgoThief ->> Pista : descripcion()
return[descripcionObtenida]

AlgoThief ->> Tiempo : tiempoTranscurrido()
return[tiempoObtenido]

AlgoThief ->> AlgoThief : assertEquals("Se despliega la pista de banco", descripcionObtenida)
AlgoThief ->> AlgoThief : assertEquals(1, tiempoObtenido)
note across: La interacción del método "entrarEdificio" se puede observar en otro diagrama
@enduml