@startuml
title El detective comienza en Montreal, entra a banco y pide una pista, entra a biblioteca y pide una pista

actor "Jugador" as AlgoThief
participant ":Policia" as Policia
participant "Montreal:Ciudad" as Ciudad
participant ":Detective" as Grado
participant "sospechoso:Ladron" as Ladron


AlgoThief ->> Policia : registroPolicia("Tesoro nacional de Montreal", cantidadArrestos, Montreal, mapa)
activate Policia
Policia ->> Grado : new()
Policia ->> Ladron : new("Tesoro Nacional de Montreal")
deactivate Policia
AlgoThief ->> Policia : anotarGenero("Femenino")
loop entra dos veces al banco
AlgoThief ->> Policia : entrarEdificio("banco")
activate Policia
Policia ->> Ciudad : visitar("banco", Detective)
return [1]
end
deactivate Policia
AlgoThief ->> AlgoThief : assertEquals(2, tiempoEsperado)
AlgoThief ->> Policia : entrarEdificio("biblioteca")
activate Policia
Policia ->> Ciudad : visitar("biblioteca", Detective)
return [3]
deactivate Policia
AlgoThief ->> AlgoThief : assertEquals(3, tiempoEsperado)
note across: El resultado es el tiempo medido en horas
@enduml