@startuml
title El detective comienza en Montreal, entra a banco y pide una pista, entra a biblioteca y pide una pista

actor "Jugador" as AlgoThief
participant ":Policia" as Policia
participant ":Pista" as Pista
participant ":Tiempo" as Tiempo
loop entra 2 veces al banco
AlgoThief ->> Policia : entrarEdificio(banco, cronometro, dado, ciudadSiguiente)
return[pistaObtenida]

AlgoThief ->> Pista : descripcion()
return[descripcionObtenida]

AlgoThief ->> AlgoThief : assertEquals("Se despliega la pista de banco", descripcionObtenida)
end
AlgoThief ->> Tiempo : tiempoTranscurrido()
return[tiempoObtenido]

AlgoThief ->> AlgoThief : assertEquals(3, tiempoObtenido)
AlgoThief ->> Policia : entrarEdificio(biblioteca, cronometro, dado, ciudadSiguiente)
return[pistaObtenida]

AlgoThief ->> Pista : descripcion()
return[descripcionObtenida]
AlgoThief ->> AlgoThief : assertEquals("Se despliega la pista de biblioteca", descripcionObtenida)
AlgoThief ->> Tiempo : tiempoTranscurrido()
return[tiempoObtenido]

AlgoThief ->> AlgoThief : assertEquals(4, tiempoObtenido)
note across: La interacción del método "entrarEdificio" se puede observar en otro diagrama

@enduml