@startuml
title Policia visita aeropuerto 3 veces y se despliega una pista, visita puerto 55 veces y se despliega una pista
actor "Jugador" as AlgoThief
participant ":Policia" as Policia
participant ":Ciudad" as Ciudad
loop entra 3 veces a aeropuerto
AlgoThief ->> Policia : entrarEdificio("aeropuerto")
activate Policia
    Policia ->> Ciudad : visitar("aeropuerto", grado)
    return[1]
    note left: return (cant < 3 ? ++this.cant : this.cant);
deactivate Policia
end
AlgoThief ->> AlgoThief : verify(Policia, times(3)).entrarEdificio("aeropuerto)
AlgoThief ->> Policia : entrarEdificio("puerto")
loop entra 55 veces a puerto
activate Policia
    Policia ->> Ciudad : visitar("puerto", grado)
    return[1]
deactivate Policia
end
AlgoThief ->> AlgoThief : verify(Policia, times(55)).entrarEdificio("puerto)

@enduml