@startuml
title El detective visita por primera vez un Edificio

actor "Jugador" as AlgoThief
participant ":Partida" as Partida
participant ":Policia" as Policia
participant ":Mapa" as Mapa
participant ":Ciudad" as Ciudad
participant "GradoDePolicia" as GradoDePolicia
participant "LugarDeInteres" as LugarDeInteres
participant ":Pista" as Pista

AlgoThief ->> Partida: viajar(ciudadDestino)
Partida ->> Policia: viajar(ciudadDestino)
activate Policia

Policia ->> Mapa: calcularDistancia(ciudadActual, ciudadDestino)
Policia <-- Mapa: [kms]
Policia ->> GradoDePolicia: calcularTiempo(kms)
Policia <-- GradoDePolicia: [tiempo]
return [tiempo]
deactivate Policia
AlgoThief ->> Partida: entrarEdificio(lugarSeleccionado)
Partida ->> Policia: entrarEdificio(lugarSeleccionado)
activate Policia
Policia ->> Ciudad: visitar(lugarSeleccionado,grado)
Ciudad ->> LugarDeInteres: visitar(grado)
loop [se busca en todas las pistas]
	LugarDeInteres ->> Pista: buscarPista(grado)
end
Policia ->> Policia: tiempoDeVisita(cantLugaresVisitados)
Pista --> AlgoThief : [Pista]
Policia --> Partida : [tiempo]
deactivate Policia




@enduml