@startuml
title Cargar datos recopilados en la computadora y buscar sospechosos

actor "Jugador" as AlgoThief
participant "femenino:Cualidad" as Cualidad
participant ":Policia" as Policia
participant ":Sospechoso" as Sospechoso

AlgoThief ->> Cualidad : new("Femenino")

AlgoThief ->> Policia : anotarCualidad(femenino)
activate Policia
Policia ->> Sospechoso : anotarCualidad(femenino)
deactivate Policia

AlgoThief ->> Policia : buscarLadrones(comisaria)
note across : La interacción de este método se detalla en otro diagrama aparte
return[List<Ladron>]
AlgoThief ->> AlgoThief : assertEquals(listaEsperada, List<Ladron>)

note across: Los datos pueden variar, en este caso se decidio filtrar sospechosos con genero femenino


@enduml