@startuml
title Detective toma un caso y realiza la investigación completa

actor "Jugador" as AlgoThief
participant ":Policia" as Policia
participant ":Sospechoso" as Sospechoso
participant "OrdenDeArresto" as Orden


AlgoThief ->> Policia : entrarEdificio(Banco, cronometro, dado)
note across : La interacción de este método se detalla en otro diagrama aparte

Policia --> AlgoThief : [pistaObtenidaDelBanco]


AlgoThief ->> Policia : viajar(Montreal, mapa, cronometro)
note across : La interacción de este método se detalla en otro diagrama aparte

AlgoThief ->> Policia : anotarCualidad(femenino)
activate Policia
    Policia ->> Sospechoso : anotarCualidad(femenino)
deactivate Policia
AlgoThief ->> Policia : buscarLadrones(comisaria)
note across : La interacción de este método se detalla en otro diagrama aparte
return[List<Ladron>]

AlgoThief ->> Policia : atrapar()
activate Policia
    Policia ->> Orden : emitida()
    Orden --> Policia : [resultado]
deactivate Policia
Policia --> AlgoThief : [resultado]
AlgoThief ->> AlgoThief : assertTrue(resultado)
AlgoThief ->> AlgoThief : assertEquals(pistaEsperada, pistaObtenidaDelBanco)

note across: Los datos pueden variar, en este caso se decidio filtrar sospechosos con genero femenino


@enduml