@startuml
title Detective sufre herida de cuchillo y luego no puede dormir

actor "Jugador" as AlgoThief
participant ":Policia" as Policia
participant ":Sospechoso" as Sospechoso
participant ":Tiempo" as Tiempo
AlgoThief ->> Policia : recibirCuchillazo(cronometro)
AlgoThief ->> Tiempo : tiempoTranscurrido
return[tiempoTranscurrido]
AlgoThief ->> AlgoThief : assertEquals(2, tiempoTranscurrido)

AlgoThief ->> Tiempo : tiempoFormateado
return[tiempoFormateado]
AlgoThief ->> AlgoThief : assertEquals("Monday, 09 Hs", tiempoFormateado)

AlgoThief ->> Policia : dormir(cronometro)
AlgoThief ->> Tiempo : tiempoTranscurrido
return[tiempoTranscurrido]
AlgoThief ->> AlgoThief : assertEquals(2, tiempoTranscurrido)

@enduml