@startuml
title Policia intenta atrapar a un sospechoso sin emitir orden de arresto

actor "Jugador" as AlgoThief
participant ":Policia" as Policia
participant ":Sospechoso" as Sospechoso
participant ":OrdenSinEmitir" as Orden
AlgoThief ->> Policia : anotarCualidad(masculino)
activate Policia
    Policia ->> Sospechoso : anotarCualidad()
deactivate Policia
AlgoThief ->> Policia : buscarLadrones(comisaria)
return[ladronesObtenidos]
AlgoThief ->> AlgoThief : assertEquals(ladronesEsperados, ladronesObtenidos)

AlgoThief ->> Ruta : new()
return[ruta]
AlgoThief ->> Policia : comprobarVictoria(ruta)
activate Policia
    Policia ->> Orden : emitida()
    Orden --> Policia : [false]
    Policia ->> Ruta : estamosEnUltimaCiudad()
    Ruta --> Policia : [true]
    return[resultado]
deactivate Policia

AlgoThief ->> AlgoThief : assertFalse(resultado)
note across: En el caso mostrado, el jugador pierde ya que no tenía un solo ladron en su lista
@enduml