@startuml
title Policia intenta atrapar a un sospechoso sin emitir orden de arresto

actor "Jugador" as AlgoThief
participant ":Policia" as Policia
participant ":Sospechoso" as Sospechoso
participant "OrdenDeArresto" as Orden
AlgoThief ->> Policia : anotarCualidad(masculino)
activate Policia
    Policia ->> Sospechoso : anotarCualidad()
deactivate Policia
AlgoThief ->> Policia : buscarLadrones(comisaria)
return[ladronesObtenidos]
AlgoThief ->> AlgoThief : assertEquals(ladronesEsperados, ladronesObtenidos)
AlgoThief ->> Policia : atrapar()
activate Policia
    Policia ->> Orden : emitida()
    Orden --> Policia : [resultado]
deactivate Policia
Policia --> AlgoThief : [resultado]

AlgoThief ->> AlgoThief : assertFalse(resultado)
@enduml