@startuml
title Investigador toma caso y viaja de Montreal a Mexico

actor "Jugador" as AlgoThief
participant ":Policia" as Policia
participant ":Tiempo" as Tiempo
AlgoThief ->> Policia : viajar(ciudadDeMexico, mapa, cronometro)
note across : La interacción de este método se detalla en otro diagrama aparte


AlgoThief ->> Tiempo : tiempoFormateado()
return[tiempoRecibido]

AlgoThief ->> AlgoThief : assertEquals("Monday 15 Hs.", tiempoRecibido)
@enduml